// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKv7pp7ArsHGXLJoDCspw4dTmsEYwbP5Q',
    appId: '1:140975787490:web:08f31f9f397c1c2b947dbb',
    messagingSenderId: '140975787490',
    projectId: 'wselha-58f90',
    authDomain: 'wselha-58f90.firebaseapp.com',
    storageBucket: 'wselha-58f90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOejgNAG43xkFc6G0tZZXnlSAmGuUIYg',
    appId: '1:140975787490:android:6e44011a3d6bb696947dbb',
    messagingSenderId: '140975787490',
    projectId: 'wselha-58f90',
    storageBucket: 'wselha-58f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_q_jBPYzrradGeEC4cgxe2Dx2m3pc5U',
    appId: '1:140975787490:ios:d4010d6d5f4e869e947dbb',
    messagingSenderId: '140975787490',
    projectId: 'wselha-58f90',
    storageBucket: 'wselha-58f90.appspot.com',
    iosClientId: '140975787490-gfda7ui8buqjujvmn0guhodn0cmte6lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wselha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy_q_jBPYzrradGeEC4cgxe2Dx2m3pc5U',
    appId: '1:140975787490:ios:d4010d6d5f4e869e947dbb',
    messagingSenderId: '140975787490',
    projectId: 'wselha-58f90',
    storageBucket: 'wselha-58f90.appspot.com',
    iosClientId: '140975787490-gfda7ui8buqjujvmn0guhodn0cmte6lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wselha',
  );
}
